### ISSUE TITLE
Repo key not accepted when bullseye-samba414 attempted

### ISSUE THREAD

**Issue by Jibun-no-Kage** [thctlo/samba4#10]
Can't install the key per the website documentation.  Or the key file is some how incorrect?  The website steps work fine for repo setup on Buster but apparently not on Bullseye?

Tried...
\# wget -O- https://apt.van-belle.nl/louis-van-belle.gpg-key.asc |    gpg --dearmor | sudo tee /usr/share/keyrings/louis-van-belle.gpg > /dev/null

And the file is created, but the key fails or appears to be rejected when repo update attempted...

\# nano /etc/apt/sources.list.d/van-belle.list
\# AptVanBelle repo for samba...
deb http://apt.van-belle.nl/debian bullseye-samba414 main contrib non-free

\# apt update
Hit:1 http://raspbian.raspberrypi.org/raspbian bullseye InRelease
Hit:2 http://archive.raspberrypi.org/debian bullseye InRelease
Get:3 http://apt.van-belle.nl/debian bullseye-samba414 InRelease [12.0 kB]
Err:3 http://apt.van-belle.nl/debian bullseye-samba414 InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY FF620912DC8D81F8
Reading package lists... Done
W: GPG error: http://apt.van-belle.nl/debian bullseye-samba414 InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY FF620912DC8D81F8
E: The repository 'http://apt.van-belle.nl/debian bullseye-samba414 InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

I used '[trusted=yes]' to enable use of the repo, but this is not a good practice of course.

**Comment by thctlo** [comment]
Sorry for the late reply. 

apt line has change to the way Debian wants it. 
remove the old line and use : 

`echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/louis-van-belle.gpg] http://apt.van-belle.nl/debian/ $(lsb_release -sc)-samba414 main" | sudo tee -a /etc/apt/sources.list.d/van-belle.list`

It's one line.. 

Let me know it of worked for you.

**Comment by Jibun-no-Kage** [comment]
Totally cool, thanks for getting to this.  Appears to work.

deb [arch=armhf signed-by=/usr/share/keyrings/louis-van-belle.gpg] http://apt.van-belle.nl/debian/ bullseye-samba414 main
