### ISSUE TITLE
backup file should not be world readable

### ISSUE THREAD

**Issue by jkirk** [thctlo/samba4#6]
At least `secrets.tdb` contains [sensitive information](https://wiki.samba.org/index.php/TDB_Locations) and should be protected. I think the permission of the created tar-file should be something like `0640` or even `0600`.

**Comment by thctlo** [comment]
Good point, i'll have a look at that.

**Comment by thctlo** [comment]
Hai, I changed backup folder to root:staff 660 
https://github.com/thctlo/samba4/commit/9ce480711a25aec20f88f8d72ab9513465d7ee56#diff-0c320061b563c560eba11b84e2a4f2f9
